### ISSUE TITLE
User search does not work against CROWD 2.10.1

### ISSUE THREAD

**Issue by borgeorgiev** [PatrickRoumanoff/nexus-crowd-plugin#26]
I'm using the plugin with Crowd 2.10.1 and when I try to search for users there are exceptions in the log indicating that 2 attributes returned by the REST API of crowd are not supported - not in the UserResponse JAXB bean.
* created-date
* updated-date

I've implemented a patch and uploaded the patched jar and everything works as expected. The change was to add the missing fields to the UserResponse bean. 

plugin version: 3.1.0
nexus : OSS 3.2.0-01

```
2017-02-01 18:17:45,580+0000 DEBUG [qtp165439263-74] admin org.sonatype.nexus.plugins.crowd.client.rest.RestClient - searchUsers(bo)
2017-02-01 18:17:45,580+0000 DEBUG [qtp165439263-74] admin org.sonatype.nexus.plugins.crowd.client.rest.RestClient - http://172.31.43.155:8095/crowd/rest/usermanagement/1/search?entity-type=user&max-results=1000&restriction=active%3Dtrue+AND+name%3D%22bo*%22&start-index=0
2017-02-01 18:17:45,655+0000 DEBUG [qtp165439263-74] admin org.sonatype.nexus.plugins.crowd.client.rest.RestClient - getUser(borgeorgiev)
2017-02-01 18:17:45,655+0000 DEBUG [qtp165439263-74] admin org.sonatype.nexus.plugins.crowd.client.rest.RestClient - http://172.31.43.155:8095/crowd/rest/usermanagement/1/user?username=borgeorgiev
2017-02-01 18:17:45,675+0000 INFO  [qtp165439263-74] admin javax.xml.bind.helpers.DefaultValidationEventHandler - DefaultValidationEventHandler: [ERROR]: unexpected element (uri:"", local:"created-date"). Expected elements are <{}password>,<{}display-name>,<{}link>,<{}active>,<{}attributes>,<{}key>,<{}first-name>,<{}email>,<{}last-name> 
     Location: line 1
2017-02-01 18:17:45,676+0000 ERROR [qtp165439263-74] admin org.sonatype.nexus.plugins.crowd.client.rest.RestClient - Error occured while consuming Crowd REST service
javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"created-date"). Expected elements are <{}password>,<{}display-name>,<{}link>,<{}active>,<{}attributes>,<{}key>,<{}first-name>,<{}email>,<{}last-name>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.childElement(Loader.java:90) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.childElement(StructureLoader.java:237) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) [na:1.8.0_121]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221) [na:1.8.0_121]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276) [na:1.8.0_121]
	at org.sonatype.nexus.plugins.crowd.client.rest.RestClient.unmarshal(RestClient.java:471) [com.roumanoff.nexus.crowd-plugin:3.1.0]
	at org.sonatype.nexus.plugins.crowd.client.rest.RestClient.getUser(RestClient.java:266) [com.roumanoff.nexus.crowd-plugin:3.1.0]
	at org.sonatype.nexus.plugins.crowd.client.rest.CachingRestClient.getUser(CachingRestClient.java:79) [com.roumanoff.nexus.crowd-plugin:3.1.0]
	at org.sonatype.nexus.plugins.crowd.client.rest.RestClient.searchUsers(RestClient.java:326) [com.roumanoff.nexus.crowd-plugin:3.1.0]
	at org.sonatype.nexus.plugins.crowd.security.CrowdUserManager.searchUsers(CrowdUserManager.java:96) [com.roumanoff.nexus.crowd-plugin:3.1.0]
```

**Comment by PatrickRoumanoff** [comment]
Sounds good - do you have a PR for the patch?

**Comment by flopma** [comment]
Would be good to make the changes so that the code still works for previous Crowd version. Maybe some annotation can describe those new fields as optional?

**Comment by PatrickRoumanoff** [comment]
I am happy to force a newer version of crowd.
We can always add a comment in the code for people who need to support
older versions to take those new fields out.
