### ISSUE TITLE
Use against embedded Crowd

### ISSUE THREAD

**Issue by briantopping** [PatrickRoumanoff/nexus-crowd-plugin#8]
Great plugin, have been using it for a while against native Crowd, thanks.  Switched over this week to using embedded Crowd in Jira 6.0.1 (using the "JIRA User Server"), but connecting nexus-crowd-plugin to it causes that version of Crowd to crash.  

Stack trace from JIRA:

java.lang.NullPointerException
    at com.atlassian.crowd.plugin.rest.service.controller.TokenController.createSessionEntityWithMinimalUser(TokenController.java:221)
    at com.atlassian.crowd.plugin.rest.service.controller.TokenController.authenticateUser(TokenController.java:67)
    at com.atlassian.crowd.plugin.rest.service.resource.TokenResource.authenticateUser(TokenResource.java:101)
    at sun.reflect.GeneratedMethodAccessor1525.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.atlassian.plugins.rest.common.interceptor.impl.DispatchProviderHelper$ResponseOutInvoker$1.invoke(DispatchProviderHelper.java:234)
    at com.atlassian.plugins.rest.common.interceptor.impl.DispatchProviderHelper$1.intercept(DispatchProviderHelper.java:100)
    at com.atlassian.plugins.rest.common.interceptor.impl.DefaultMethodInvocation.invoke(DefaultMethodInvocation.java:61)
    at com.atlassian.plugins.rest.common.expand.interceptor.ExpandInterceptor.intercept(ExpandInterceptor.java:38)
    at com.atlassian.plugins.rest.common.interceptor.impl.DefaultMethodInvocation.invoke(DefaultMethodInvocation.java:61)

**Comment by McFoggy** [comment]
@briantopping can you please share your findings? querying the SSO endpoints on our embedded Crowd in JIRA ends in this NPE.
